version: "3.8"

services:
  backend:
    build: ./back-end/rafael-eteg
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/eteg
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678

  frontend:
    build: ./front-end/customer-form
    ports:
      - "3000:80"